// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly.Outputs
{

    [OutputType]
    public sealed class GetEnvironmentApprovalSettingResult
    {
        public readonly bool CanApplyDeclinedChanges;
        public readonly bool CanReviewOwnRequest;
        public readonly int MinNumApprovals;
        public readonly bool Required;
        public readonly ImmutableArray<string> RequiredApprovalTags;
        public readonly ImmutableDictionary<string, object> ServiceConfig;
        public readonly string ServiceKind;

        [OutputConstructor]
        private GetEnvironmentApprovalSettingResult(
            bool canApplyDeclinedChanges,

            bool canReviewOwnRequest,

            int minNumApprovals,

            bool required,

            ImmutableArray<string> requiredApprovalTags,

            ImmutableDictionary<string, object> serviceConfig,

            string serviceKind)
        {
            CanApplyDeclinedChanges = canApplyDeclinedChanges;
            CanReviewOwnRequest = canReviewOwnRequest;
            MinNumApprovals = minNumApprovals;
            Required = required;
            RequiredApprovalTags = requiredApprovalTags;
            ServiceConfig = serviceConfig;
            ServiceKind = serviceKind;
        }
    }
}
