// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly.Outputs
{

    [OutputType]
    public sealed class GetFeatureFlagEnvironmentRuleClauseResult
    {
        public readonly string Attribute;
        public readonly string? ContextKind;
        public readonly bool? Negate;
        public readonly string Op;
        public readonly string? ValueType;
        public readonly ImmutableArray<string> Values;

        [OutputConstructor]
        private GetFeatureFlagEnvironmentRuleClauseResult(
            string attribute,

            string? contextKind,

            bool? negate,

            string op,

            string? valueType,

            ImmutableArray<string> values)
        {
            Attribute = attribute;
            ContextKind = contextKind;
            Negate = negate;
            Op = op;
            ValueType = valueType;
            Values = values;
        }
    }
}
