// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly.Outputs
{

    [OutputType]
    public sealed class GetSegmentRuleResult
    {
        public readonly string? BucketBy;
        public readonly ImmutableArray<Outputs.GetSegmentRuleClauseResult> Clauses;
        public readonly string? RolloutContextKind;
        public readonly int? Weight;

        [OutputConstructor]
        private GetSegmentRuleResult(
            string? bucketBy,

            ImmutableArray<Outputs.GetSegmentRuleClauseResult> clauses,

            string? rolloutContextKind,

            int? weight)
        {
            BucketBy = bucketBy;
            Clauses = clauses;
            RolloutContextKind = rolloutContextKind;
            Weight = weight;
        }
    }
}
