// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Launchdarkly.Outputs
{

    [OutputType]
    public sealed class ProjectEnvironmentApprovalSetting
    {
        /// <summary>
        /// Set to `true` if changes can be applied as long as the `min_num_approvals` is met, regardless of whether any reviewers have declined a request. Defaults to `true`.
        /// </summary>
        public readonly bool? CanApplyDeclinedChanges;
        /// <summary>
        /// Set to `true` if requesters can approve or decline their own request. They may always comment. Defaults to `false`.
        /// </summary>
        public readonly bool? CanReviewOwnRequest;
        /// <summary>
        /// The number of approvals required before an approval request can be applied. This number must be between 1 and 5. Defaults to 1.
        /// </summary>
        public readonly int? MinNumApprovals;
        /// <summary>
        /// Set to `true` for changes to flags in this environment to require approval. You may only set `required` to true if `required_approval_tags` is not set and vice versa. Defaults to `false`.
        /// </summary>
        public readonly bool? Required;
        /// <summary>
        /// An array of tags used to specify which flags with those tags require approval. You may only set `required_approval_tags` if `required` is not set to `true` and vice versa.
        /// </summary>
        public readonly ImmutableArray<string> RequiredApprovalTags;
        /// <summary>
        /// The configuration for the service associated with this approval. This is specific to each approval service. For a `service_kind` of `servicenow`, the following fields apply:
        /// </summary>
        public readonly ImmutableDictionary<string, object>? ServiceConfig;
        /// <summary>
        /// The kind of service associated with this approval. This determines which platform is used for requesting approval. Valid values are `servicenow`, `launchdarkly`.
        /// </summary>
        public readonly string? ServiceKind;

        [OutputConstructor]
        private ProjectEnvironmentApprovalSetting(
            bool? canApplyDeclinedChanges,

            bool? canReviewOwnRequest,

            int? minNumApprovals,

            bool? required,

            ImmutableArray<string> requiredApprovalTags,

            ImmutableDictionary<string, object>? serviceConfig,

            string? serviceKind)
        {
            CanApplyDeclinedChanges = canApplyDeclinedChanges;
            CanReviewOwnRequest = canReviewOwnRequest;
            MinNumApprovals = minNumApprovals;
            Required = required;
            RequiredApprovalTags = requiredApprovalTags;
            ServiceConfig = serviceConfig;
            ServiceKind = serviceKind;
        }
    }
}
